parameters: {}
environment: {}
packages:
  - name: ninja
    environment: {}
    parameters: {}
    actions:
      - name: catFacts
        main: ''
        runtime: 'go:default'
        environment: {}
        parameters: {}