parameters: {}
environment:
  LOG_DESTINATIONS: '[{"logtail":{"token":"<replace_with_token>"}}]'
packages:
  - name: ninja
    environment: {}
    parameters: {}
    actions:
      - name: catFacts
        main: ''
        runtime: 'go:default'
        environment: {}
        parameters: {}